name: mbuild-dev
channels:
  - conda-forge
dependencies:
  - bump2version
  - codecov
  - ele
  - gmso>=0.7.3
  - foyer>=0.11.0
  - freud>=2.0.0
  - garnett>=0.7.1
  - gsd>=2
  - hoomd=2.9.6
  - intermol
  - mdtraj
  - networkx
  - nglview>=3
  - numpy
  - openbabel>=3
  - packmol>=20
  - parmed>=3.4.3
  - pip
  - pre-commit
  - protobuf
  - py3Dmol
  - pycifrw
  - pytest
  - pytest-azurepipelines
  - pytest-cov
  - python>=3.7
  - rdkit>=2021
  - scipy
