name: mbuild-dev
channels:
  - conda-forge
  - omnia
dependencies:
  - bump2version
  - codecov
  - ele
  - gmso>=0.9.0
  - foyer>=0.11.0
  - garnett>=0.7.1
  - gsd>=2.9
  - intermol
  - mdtraj
  - networkx
  - nglview>=2.7
  - numpy=1.24.2
  - openbabel>=3.0.0
  - packmol=1!18.013
  - parmed>=3.4.3
  - pip
  - pre-commit
  - protobuf<4
  - py3Dmol
  - pycifrw
  - pytest
  - pytest-cov
  - python>=3.8
  - rdkit>=2021
  - scipy
  - treelib
