name: mbuild-dev
channels:
  - conda-forge
  - omnia
dependencies:
  - bump2version
  - codecov
  - ele
  - gmso>=0.7.3
  - foyer>=0.11.0
  - garnett>=0.7.1
  - gsd>=1.2
  - intermol
  - mdtraj
  - networkx
  - nglview>=2.7
  - numpy
  - openbabel>=3.0.0
  - packmol=1!18.013
  - parmed>=3.4.3
  - pip
  - pre-commit
  - protobuf
  - py3Dmol
  - pycifrw
  - pytest>=7.0
  - pytest-cov
  - python>=3.7
  - rdkit>=2021
  - scipy
