name: mbuild
channels:
  - conda-forge
dependencies:
  - ele
  - numpy>=2.0,<2.3
  - packmol>=20.15
  - gmso>=0.12.0
  - garnett
  - parmed>=3.4.3
  - pycifrw
  - python>=3.10,<=3.13
  - rdkit>=2021
  - scipy
  - networkx
  - treelib
