name: mbuild-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9,<=3.12
  - boltons
  - numpy>=2.0,<2.3
  - sympy
  - unyt>=2.9.5
  - boltons
  - lark>=1.2
  - lxml
  - freud>=3.0
  - intermol
  - mdtraj
  - pydantic>=2
  - networkx
  - nglview>=3
  - pytest
  - garnett>=0.7.1
  - openbabel>=3.0.0
  - openff-toolkit-base >=0.11,<0.16.7
  - openmm
  - gsd>=2.9
  - parmed>=3.4.3
  - packmol>=20.15
  - pytest-cov
  - pycifrw
  - rdkit>=2021
  - requests
  - requests-mock
  - scipy
  - treelib
  - codecov
  - matplotlib
  - ipywidgets
  - ele>=0.2.0
  - pre-commit
  - pandas
  - symengine
  - python-symengine
  - hoomd>=4.0,<5.0
  - py3Dmol
  - pip:
      - git+https://github.com/mosdef-hub/gmso.git@main
      - git+https://github.com/mosdef-hub/foyer.git@main
      - git+https://github.com/mosdef-hub/forcefield-utilities.git@main
