name: mbuild-docs
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - mock
  - nbsphinx
  - lark-parser
  - requests
  - numpydoc
  - pip
  - sphinx
  - ele
  - sphinx_rtd_theme
  - widgetsnbextension
  - pip:
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
    - cairosvg
sphinx:
  fail_on_warning: true