name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron:  "0 0 * * *"

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: mBuild Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        include:
          - os: windows-latest
            python-version: "3.12"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        name: Checkout Branch / Pull Request

      - name: Install Mamba (Linux)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          create-args: >-
            python=${{ matrix.python-version }}
        if: runner.os != 'Windows'

      - name: Install Mamba (Windows)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev-win.yml
          create-args: >-
            python=${{ matrix.python-version }}
        if: runner.os == 'Windows'

      - name: Install Package
        run: python -m pip install -e .

      - name: Test (OS -> ${{ matrix.os }} / Python -> ${{ matrix.python-version }})
        run: python -m pytest -v --cov=mbuild --cov-report=xml --cov-append --cov-config=setup.cfg --color yes --pyargs mbuild

      - name: Tests for HOOMD-blue (V3)
        run: |
          micromamba install -c conda-forge "hoomd>3"
          python -m pytest -v --cov=mbuild --cov-report=xml --cov-append --cov-config=setup.cfg --color yes mbuild/tests/test_hoomd.py
        if: runner.os == 'Linux'

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
        with:
          name: mBuild-Coverage
          verbose: true
          files: ./coverage.xml

  bleeding-edge-test:
    if: github.event.pull_request.draft == false
    name: Bleeding Edge mosdef Tests for mBuild
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        name: Checkout Branch / Pull Request

      - name: Install Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          create-args: python=3.11

      - name: Clone Foyer and GMSO
        run: |
          git clone https://github.com/mosdef-hub/foyer.git
          git clone https://github.com/mosdef-hub/gmso.git

      - name: Update Environment with foyer/gmso Dependencies
        run: |
          micromamba update --name mbuild-dev --file foyer/environment.yml
          micromamba update --name mbuild-dev --file gmso/environment.yml

      - name: Install Packages from Source
        run: |
          pip install -e foyer
          pip install -e gmso
          pip install -e .

      - name: Run Bleeding Edge Tests
        run: |
          python -m pytest -v --color yes --pyargs mbuild

  docker:
    runs-on: ubuntu-latest
    needs: test
    name: Build Docker Image
    if: github.event_name != 'pull_request'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get Tagged Version
        run: |
          echo "DOCKER_TAGS=mosdef/mbuild:${GITHUB_REF_NAME}, mosdef/mbuild:stable" >> $GITHUB_ENV
        if: github.ref_type == 'tag'

      - name: Get Push Version
        run: |
          echo "DOCKER_TAGS=mosdef/mbuild:${GITHUB_REF_NAME}, mosdef/mbuild:latest" >> $GITHUB_ENV
        if: github.ref_type == 'branch'

      - name: Docker Image Info
        run: |
          echo Docker Image tags: ${DOCKER_TAGS}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_TAGS }}
